#!/usr/bin/env tsx
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../../..');
const HOST_ROUTES = resolve(ROOT, 'apps/host/src/app/modules');
const HOST_LOADERS = resolve(ROOT, 'apps/host/src/lib/module-loaders.generated.ts');
const SLUGS = (process.env['MODULES'] ?? process.env['NEXT_PUBLIC_MODULES'] ?? '').split(',').map(s => s.trim()).filter(Boolean);

async function main() {
  await rm(HOST_ROUTES, { recursive: true, force: true });
  await mkdir(HOST_ROUTES, { recursive: true });

  for (const slug of SLUGS) {
    const moduleDir = resolve(HOST_ROUTES, slug);
    await mkdir(resolve(moduleDir, '[[...path]]'), { recursive: true });
    const pageContent = `'use client';
import { useEffect, useState, type ComponentType } from 'react';

interface Manifest {
  uiRoutes: ReadonlyArray<{ path: string; component: () => Promise<{ default: ComponentType }> }>;
}

export default function ModuleRoutePage({ params }: { params: Promise<{ path?: string[] }> }) {
  const [Component, setComponent] = useState<ComponentType | null>(null);
  useEffect(() => {
    (async () => {
      const mod = await import('@quetzal/module-${slug}/client');
      const manifest = mod.clientManifest as Manifest;
      const p = (await params).path?.join('/') ?? '';
      const route = manifest.uiRoutes.find(r => r.path === p) ?? manifest.uiRoutes[0];
      if (!route) return;
      const { default: C } = await route.component();
      setComponent(() => C);
    })();
  }, [params]);
  if (!Component) return null;
  return <Component />;
}
`;
    await writeFile(resolve(moduleDir, '[[...path]]', 'page.tsx'), pageContent, 'utf8');
    console.log(`[generate-module-routes] wrote apps/host/src/app/modules/${slug}/[[...path]]/page.tsx`);
  }

  // Static loader map over the client entry of each module (never the root index: it
  // carries the NestJS module). A template-string import(`@quetzal/module-${slug}`) in host code makes
  // webpack build a context module over the whole @quetzal/ directory (every file of every
  // workspace package, node_modules included): that is what blew the host build out of memory.
  const loaderLines = SLUGS.map((slug) => `  '${slug}': () => import('@quetzal/module-${slug}/client'),`).join('\n');
  const loadersContent = [
    '// GENERATED FILE — do not edit. Regenerated by packages/core/scripts/generate-module-routes.ts',
    '// One static entry per slug in MODULES / NEXT_PUBLIC_MODULES.',
    'export type ModuleLoader = () => Promise<{ clientManifest: unknown }>;',
    '',
    'export const moduleLoaders: Record<string, ModuleLoader> = {',
    loaderLines,
    '};',
    '',
  ].join('\n');
  await mkdir(resolve(HOST_LOADERS, '..'), { recursive: true });
  await writeFile(HOST_LOADERS, loadersContent, 'utf8');
  console.log(`[generate-module-routes] wrote apps/host/src/lib/module-loaders.generated.ts (${SLUGS.length} loaders)`);

  if (SLUGS.length === 0) {
    console.log('[generate-module-routes] no MODULES env — cleared routes dir, wrote nothing');
  }
}

main().catch(e => { console.error(e); process.exit(1); });
