#!/usr/bin/env tsx
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../../..');
const HOST_LOADERS = resolve(ROOT, 'apps/host/src/lib/module-loaders.generated.ts');
const SLUGS = (process.env['MODULES'] ?? process.env['NEXT_PUBLIC_MODULES'] ?? '').split(',').map(s => s.trim()).filter(Boolean);

// Route pages themselves are NOT generated: a single hand-written, checked-in generic
// route (apps/host/src/app/modules/[slug]/[[...path]]/page.tsx) serves every module by
// resolving the slug through the loader map below and matching uiRoutes via
// match-module-route.ts. This script only regenerates that loader map: one static
// import() per slug, never a template-string import(`@quetzal/module-${slug}`) over
// @quetzal/* (that turns into a webpack context module over the whole tree — node_modules
// included — and is what blew the host build out of memory).
async function main() {
  const loaderLines = SLUGS.map((slug) => `  '${slug}': () => import('@quetzal/module-${slug}/client'),`).join('\n');
  const loadersContent = [
    '// GENERATED FILE — do not edit. Regenerated by packages/core/scripts/generate-module-routes.ts',
    '// One static entry per slug in MODULES / NEXT_PUBLIC_MODULES.',
    'export type ModuleLoader = () => Promise<{ clientManifest: unknown }>;',
    '',
    'export const moduleLoaders: Record<string, ModuleLoader> = {',
    loaderLines,
    '};',
    '',
  ].join('\n');
  await mkdir(resolve(HOST_LOADERS, '..'), { recursive: true });
  await writeFile(HOST_LOADERS, loadersContent, 'utf8');
  console.log(`[generate-module-routes] wrote apps/host/src/lib/module-loaders.generated.ts (${SLUGS.length} loaders)`);

  if (SLUGS.length === 0) {
    console.log('[generate-module-routes] no MODULES env — wrote an empty loader map');
  }
}

main().catch(e => { console.error(e); process.exit(1); });
