-- Better-Auth 1.1.7 -> 1.7.2 (see docs/guides/1-7-upgrade-guide: account identity)

-- Account identity: add `issuer` as nullable, backfill, then enforce.
-- Credential (email/password) accounts -> 'local:credential' (accountId is already the user id).
-- Any other provider (none configured today) -> synthetic 'local:oauth:<providerId>'.
ALTER TABLE "account" ADD COLUMN "issuer" TEXT;
UPDATE "account" SET "issuer" = 'local:credential' WHERE "issuer" IS NULL AND "providerId" = 'credential';
UPDATE "account" SET "issuer" = 'local:oauth:' || "providerId" WHERE "issuer" IS NULL;
ALTER TABLE "account" ALTER COLUMN "issuer" SET NOT NULL;
CREATE UNIQUE INDEX "account_issuer_accountId_uidx" ON "account"("issuer", "accountId");
CREATE INDEX "account_userId_idx" ON "account"("userId");

-- Invitation / JWKS columns added by 1.7
ALTER TABLE "invitation" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "jwks" ADD COLUMN "alg" TEXT, ADD COLUMN "crv" TEXT, ADD COLUMN "expiresAt" TIMESTAMP(3);

-- Indexes generated by 1.7
CREATE INDEX "invitation_organizationId_idx" ON "invitation"("organizationId");
CREATE INDEX "invitation_email_idx" ON "invitation"("email");
CREATE INDEX "member_organizationId_idx" ON "member"("organizationId");
CREATE INDEX "member_userId_idx" ON "member"("userId");
CREATE INDEX "session_userId_idx" ON "session"("userId");
CREATE INDEX "verification_identifier_idx" ON "verification"("identifier");
