#!/usr/bin/env tsx
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const SCHEMA = resolve(import.meta.dirname, '../prisma/schema.prisma');
const OUT = resolve(import.meta.dirname, '../src/model-tenant-registry.ts');

async function main() {
  const src = await readFile(SCHEMA, 'utf8');
  const models: Record<string, boolean> = {};

  const modelBlocks = [...src.matchAll(/model\s+(\w+)\s*\{([^}]+)\}/g)];
  for (const [, name, body] of modelBlocks) {
    const clientName = name.charAt(0).toLowerCase() + name.slice(1);
    models[clientName] = /^\s*tenantId\s+/m.test(body);
  }

  const content = `// GENERATED — do not edit.
// Regenerated by packages/db/scripts/generate-tenant-registry.ts
// Maps Prisma client model name → whether it has a tenantId column.

export const MODEL_HAS_TENANT_ID: Readonly<Record<string, boolean>> = ${JSON.stringify(models, null, 2)} as const;

export function modelHasTenantId(model: string): boolean {
  return MODEL_HAS_TENANT_ID[model] === true;
}
`;
  await writeFile(OUT, content, 'utf8');
  console.log(`[generate-tenant-registry] wrote ${OUT} (${Object.keys(models).length} models)`);
}

main().catch(e => { console.error(e); process.exit(1); });
