#!/usr/bin/env tsx
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../../..');
const OUT = resolve(import.meta.dirname, '../prisma/schema.prisma');
const AUTH = resolve(ROOT, 'packages/auth/prisma/auth.prisma');
const CORE = resolve(import.meta.dirname, '../prisma/core.prisma');

const HEADER = `// GENERATED FILE — do not edit manually.
// Regenerated by packages/db/scripts/merge-schemas.ts
// Sources: packages/auth/prisma/auth.prisma + packages/db/prisma/core.prisma + packages/module-*/prisma/models.prisma

generator client {
  provider = "prisma-client-js"
  previewFeatures = []
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;

async function readIfExists(path: string): Promise<string> {
  try {
    const content = await readFile(path, 'utf8');
    return content.replace(/generator\s+\w+\s*\{[^}]*\}/g, '').replace(/datasource\s+\w+\s*\{[^}]*\}/g, '').trim();
  } catch {
    return '';
  }
}

async function discoverModulePrismas(): Promise<string[]> {
  const packagesDir = resolve(ROOT, 'packages');
  const entries = await readdir(packagesDir, { withFileTypes: true });
  const modules = entries.filter(e => e.isDirectory() && e.name.startsWith('module-'));
  const paths: string[] = [];
  for (const m of modules) {
    const candidate = join(packagesDir, m.name, 'prisma/models.prisma');
    try {
      await readFile(candidate);
      paths.push(candidate);
    } catch {}
  }
  return paths;
}

async function main() {
  const parts = [HEADER];
  parts.push(`// --- @quetzal/auth (Better-Auth generated) ---\n`);
  parts.push(await readIfExists(AUTH));
  parts.push(`\n\n// --- @quetzal/db core ---\n`);
  parts.push(await readIfExists(CORE));

  for (const path of await discoverModulePrismas()) {
    const slug = path.match(/packages\/module-([^/]+)\/prisma/)?.[1];
    parts.push(`\n\n// --- @quetzal/module-${slug} ---\n`);
    parts.push(await readIfExists(path));
  }

  await writeFile(OUT, parts.join('\n'), 'utf8');
  console.log(`[schema:merge] wrote ${OUT}`);
}

main().catch(e => { console.error(e); process.exit(1); });
